package org.firstinspires.ftc.teamcode.Skystone.Auto.Actions.Enums;

public enum ActionType {
    EXTEND_OUTTAKE, DROPSTONE_AND_RETRACT_OUTTAKE, RELEASE_FOUNDATION, START_INTAKE, STOP_INTAKE, EXTEND_FOUNDATION, RESET_OUTTAKE, RAISE_OUTTAKE_LEVEL1, RAISE_OUTTAKE_LEVEL2
}
